// Generates supabase/migrations/…_seed.sql from the prototype's real moments (src/seed.ts).
// Only the moments, organisations and extra fields: no invented reactions, comments or signals.
// Run: npx tsx scripts/gen-seed-sql.ts
import { writeFileSync } from 'node:fs';
import { SEED_FIELD_DEFS, SEED_MOMENTS } from '../src/seed';
import { COORDINATOR_ORG, ROLES } from '../src/roles';
import { orgsOf } from '../src/lib/moments';

const THEMADAG = 'Internationale themadag';

const q = (v: string | null | undefined) => (v === null || v === undefined ? 'null' : `'${v.replace(/'/g, "''")}'`);
const b = (v: boolean) => (v ? 'true' : 'false');
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const json = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;

// Organisations: everyone involved in a seed moment, plus the demo partners and the coordinators.
const orgs = new Map<string, boolean>();
for (const m of SEED_MOMENTS) {
  for (const o of orgsOf(m)) if (o !== THEMADAG && !orgs.has(o)) orgs.set(o, m.isGreenDealPartner);
}
for (const r of ROLES) if (r.org && !orgs.has(r.org)) orgs.set(r.org, r.org !== COORDINATOR_ORG);

const lines: string[] = [
  '-- Generated by scripts/gen-seed-sql.ts from src/seed.ts. Do not edit by hand.',
  '-- The real moments from the partners\' shared sheet (organisation names only).',
  '',
  'insert into public.organisations (name, is_green_deal_partner) values',
  [...orgs].map(([name, gd]) => `  (${q(name)}, ${b(gd)})`).join(',\n') + '\non conflict (name) do nothing;',
  '',
  'insert into public.field_defs (id, name, type, options, show_in_form) values',
  SEED_FIELD_DEFS.map((f) => `  (${q(f.id)}, ${q(f.name)}, ${q(f.type)}, ${arr(f.options)}, ${b(f.showInForm)})`).join(',\n') +
    '\non conflict (id) do nothing;',
  '',
  '-- Seed rows keep their original "created by" and must not notify anyone.',
  'alter table public.moments disable trigger guard_moment;',
  'alter table public.moments disable trigger notify_moment;',
  '',
  'insert into public.moments (id, title, start_date, end_date, ongoing, date_unsure, unsure_note, type, target_group, focus, free, region,',
  '  organiser, co_organisers, owner_orgs, is_green_deal_partner, link, description, halfhalf_link, need, featured, custom_fields, created_by_org, created_at) values',
  SEED_MOMENTS.map(
    (m) =>
      `  (${[
        q(m.id),
        q(m.title),
        q(m.startDate),
        q(m.endDate),
        b(m.ongoing),
        b(m.dateUnsure),
        q(m.unsureNote),
        q(m.type),
        q(m.targetGroup),
        q(m.focus),
        b(m.free),
        q(m.region),
        q(m.organiser),
        q(m.coOrganisers),
        arr(orgsOf(m)),
        b(m.isGreenDealPartner),
        q(m.link),
        q(m.description),
        b(m.halfhalfLink),
        q(m.need),
        b(m.featured),
        json(m.customFields),
        q(m.createdBy),
        q(m.createdAt),
      ].join(', ')})`,
  ).join(',\n') + '\non conflict (id) do nothing;',
  '',
  'alter table public.moments enable trigger guard_moment;',
  'alter table public.moments enable trigger notify_moment;',
  '',
];

const out = 'supabase/migrations/20260925000002_seed.sql';
writeFileSync(out, lines.join('\n'));
console.log(`✔ ${out}: ${orgs.size} organisaties, ${SEED_FIELD_DEFS.length} velden, ${SEED_MOMENTS.length} momenten`);
