// Demo data. Moments come from the partners' shared sheet (organisation names only,
// no personal contact details). Reactions, comments and signals are invented so the
// matches view and notifications have something to show.
import type { AppState, AppNotification, Comment, FieldDef, Moment, Reaction, Signal } from './types';
import { COORDINATOR_ORG } from './roles';

export const STATE_VERSION = 1;

const T = (d: string, time = '10:00') => `${d}T${time}:00`;

type SeedMoment = Omit<Moment, 'customFields' | 'createdBy' | 'createdAt' | 'free' | 'region' | 'isGreenDealPartner' | 'halfhalfLink' | 'featured' | 'ongoing' | 'dateUnsure'> &
  Partial<Pick<Moment, 'customFields' | 'createdBy' | 'createdAt' | 'free' | 'region' | 'isGreenDealPartner' | 'halfhalfLink' | 'featured' | 'ongoing' | 'dateUnsure'>>;

function moment(m: SeedMoment): Moment {
  return {
    customFields: {},
    createdBy: m.organiser,
    createdAt: T('2026-09-01'),
    free: true,
    region: 'Vlaanderen',
    isGreenDealPartner: true,
    halfhalfLink: false,
    featured: false,
    ongoing: false,
    dateUnsure: false,
    ...m,
  };
}

const THEMADAG = 'Internationale themadag';

export const SEED_FIELD_DEFS: FieldDef[] = [
  { id: 'f-taal', name: 'Taal', type: 'dropdown', options: ['Nederlands', 'Frans', 'Engels', 'Meertalig'], showInForm: true },
  { id: 'f-pers', name: 'Persmoment voorzien', type: 'yesno', options: [], showInForm: true },
];

export const SEED_MOMENTS: Moment[] = [
  moment({
    id: 'm-webinar-upf',
    title: "Webinar 'Een open dialoog over voeding, ultrabewerkt en gezondheid'",
    startDate: '2026-09-23',
    type: 'Webinar',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    region: 'Online',
    organiser: 'Mosquito In The Room',
    description: 'Online gesprek over voeding, ultrabewerkte producten en gezondheid.',
    customFields: { 'f-taal': 'Nederlands' },
  }),
  moment({
    id: 'm-goodplanet',
    title: 'Samenwerking GoodPlanet, Delhaize en Artevelde',
    startDate: '2026-09-22',
    type: 'Persbericht',
    targetGroup: 'Media',
    focus: 'halfhalf',
    organiser: 'Delhaize',
    coOrganisers: 'GoodPlanet, Artevelde',
    halfhalfLink: true,
    link: 'https://www.delhaize.be',
    description: 'Gezamenlijk persbericht over de samenwerking tussen GoodPlanet, Delhaize en Artevelde.',
    customFields: { 'f-pers': 'ja' },
  }),
  moment({
    id: 'm-on-a-budget',
    title: "Campagne 'On a budget'",
    startDate: '2026-09-01',
    ongoing: true,
    type: 'Campagne',
    targetGroup: 'Consument',
    focus: '100% plantaardig',
    organiser: 'Lidl',
    coOrganisers: 'ProVeg',
    link: 'https://www.lidl.be',
    description: 'Campagne rond betaalbaar plantaardig eten.',
    createdBy: 'Lidl',
    customFields: { 'f-taal': 'Meertalig' },
  }),
  moment({
    id: 'm-smos',
    title: "Campagne 'Smos alles'",
    startDate: '2026-09-14',
    endDate: '2026-11-08',
    type: 'Campagne',
    targetGroup: 'Consument',
    focus: 'breder eiwitshift',
    organiser: 'VLAM',
    link: 'https://www.vlam.be',
    description: 'Focus: breder dan volledig vegetarisch.',
  }),
  moment({
    id: 'm-taste-truck',
    title: 'Taste Truck',
    startDate: null,
    ongoing: true,
    type: 'Event',
    targetGroup: 'Consument',
    focus: '100% plantaardig',
    organiser: 'GAIA',
    link: 'https://www.gaia.be',
    need: 'Event met min. 500 bezoekers? De taste truck is gratis.',
    description: 'Foodtruck met plantaardige proevertjes, gratis te boeken voor evenementen.',
  }),
  moment({
    id: 'm-veggiedag',
    title: 'Wereld Veggiedag',
    startDate: '2026-10-01',
    type: 'Themadag',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: THEMADAG,
    isGreenDealPartner: false,
    createdBy: COORDINATOR_ORG,
  }),
  moment({
    id: 'm-superlijst',
    title: 'Publicatie Superlijst Milieu II',
    startDate: '2026-10-06',
    type: 'Publicatie',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: 'Questionmark',
    coOrganisers: 'Rikolto',
    need: 'Mee verspreiden via eigen kanalen',
    description: 'Tweede editie van de Superlijst Milieu.',
    customFields: { 'f-pers': 'ja' },
  }),
  moment({
    id: 'm-food-chains',
    title: "Event 'Plant-Based Food Chains'",
    startDate: '2026-10-07',
    endDate: '2026-10-08',
    type: 'Event',
    targetGroup: 'Professionals',
    focus: '100% plantaardig',
    free: false,
    organiser: 'Run and Harvest',
    isGreenDealPartner: false,
    description: 'Tweedaags event voor de voedselketen en het beleid.',
    customFields: { 'f-taal': 'Engels' },
  }),
  moment({
    id: 'm-aardappel',
    title: 'Aardappelcampagne',
    startDate: '2026-10-14',
    endDate: '2026-11-14',
    type: 'Campagne',
    targetGroup: 'Consument',
    focus: 'breder eiwitshift',
    organiser: 'VLAM',
    link: 'https://www.vlam.be',
  }),
  moment({
    id: 'm-pure-plant',
    title: "We're Smart Pure Plant Days (Brugge)",
    startDate: '2026-10-25',
    endDate: '2026-10-27',
    type: 'Event',
    targetGroup: 'Breed',
    focus: '100% plantaardig',
    region: 'West-Vlaanderen',
    organiser: "We're Smart",
    coOrganisers: 'Stad Brugge',
    isGreenDealPartner: false,
    customFields: { 'f-taal': 'Meertalig' },
  }),
  moment({
    id: 'm-verrassend',
    title: "Workshop 'Verrassend Plantaardig'",
    startDate: '2026-10-27',
    type: 'Workshop',
    targetGroup: 'Chefs & grootkeukens',
    focus: '100% plantaardig',
    organiser: 'JAVA Foodservice',
    coOrganisers: 'Ardo',
    description: 'Workshop voor chefs en grootkeukens.',
  }),
  moment({
    id: 'm-campus-v-cup',
    title: 'Campus V Cup',
    startDate: '2026-11-01',
    dateUnsure: true,
    unsureNote: 'meerdaags',
    type: 'Campagne',
    targetGroup: 'Hoger onderwijs',
    focus: '100% plantaardig',
    organiser: 'ProVeg',
    featured: true,
    need: '15 hogescholen/universiteiten doen mee; wie iets wil organiseren op de campussen, neem contact op.',
    description: 'Meerdaagse campagne op hogescholen en universiteiten.',
    createdBy: 'ProVeg',
  }),
  moment({
    id: 'm-vegan-day',
    title: 'World Vegan Day',
    startDate: '2026-11-01',
    type: 'Themadag',
    targetGroup: 'Breed',
    focus: '100% plantaardig',
    organiser: THEMADAG,
    isGreenDealPartner: false,
    createdBy: COORDINATOR_ORG,
  }),
  moment({
    id: 'm-ilvo',
    title: "Studiedag 'Plantaardige vleesanalogen'",
    startDate: '2026-11-12',
    type: 'Workshop',
    targetGroup: 'Professionals',
    focus: 'breder eiwitshift',
    organiser: 'ILVO',
    link: 'https://ilvo.vlaanderen.be',
    description: 'Studiedag over plantaardige vleesanalogen.',
  }),
  moment({
    id: 'm-voorschrift',
    title: "Congres 'Voeding op voorschrift'",
    startDate: '2026-12-15',
    type: 'Event',
    targetGroup: 'Zorg',
    focus: 'breder eiwitshift',
    free: false,
    organiser: 'Mosquito In The Room',
  }),
  moment({
    id: 'm-public-plates',
    title: 'Public Plates Forum',
    startDate: '2026-12-15',
    type: 'Event',
    targetGroup: 'Professionals',
    focus: 'breder eiwitshift',
    region: 'Brussel',
    organiser: 'Climate Group',
    isGreenDealPartner: false,
    description: 'Forum over duurzame maaltijden in publieke keukens.',
    customFields: { 'f-taal': 'Engels' },
  }),
  moment({
    id: 'm-goed-eten',
    title: 'Week voor Goed Eten',
    startDate: '2027-01-15',
    endDate: '2027-01-24',
    type: 'Campagne',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: 'Rikolto',
  }),
  moment({
    id: 'm-peulvrucht',
    title: 'Week van de Peulvrucht',
    startDate: '2027-02-08',
    endDate: '2027-02-14',
    type: 'Campagne',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: 'Vlaams Instituut Gezond Leven',
    halfhalfLink: true,
    featured: true,
    link: 'https://www.gezondleven.be',
    description: 'Een week lang aandacht voor peulvruchten.',
    customFields: { 'f-taal': 'Nederlands', 'f-pers': 'ja' },
  }),
  moment({
    id: 'm-bonen',
    title: "Campagne 'Beans & Pulses – Wie is er bang van bonen?'",
    startDate: '2027-02-01',
    dateUnsure: true,
    type: 'Campagne',
    targetGroup: 'Consument',
    focus: '100% plantaardig',
    organiser: 'ProVeg',
    createdBy: 'ProVeg',
  }),
  moment({
    id: 'm-pulses-day',
    title: 'World Pulses Day',
    startDate: '2027-02-10',
    type: 'Themadag',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: THEMADAG,
    isGreenDealPartner: false,
    createdBy: COORDINATOR_ORG,
  }),
  moment({
    id: 'm-dietist',
    title: 'Week van de Diëtist',
    startDate: '2027-03-15',
    endDate: '2027-03-22',
    type: 'Campagne',
    targetGroup: 'Zorg',
    focus: 'breder eiwitshift',
    organiser: 'VBVD',
  }),
  moment({
    id: 'm-overshoot',
    title: 'Earth Overshoot Day (België)',
    startDate: '2027-04-11',
    type: 'Themadag',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: THEMADAG,
    isGreenDealPartner: false,
    createdBy: COORDINATOR_ORG,
  }),
  moment({
    id: 'm-toekomstproef',
    title: 'Toekomstproef – inspiratie-event voor grootkeukens',
    startDate: '2027-05-01',
    dateUnsure: true,
    unsureNote: '11 of 12 mei',
    type: 'Event',
    targetGroup: 'Chefs & grootkeukens',
    focus: 'breder eiwitshift',
    organiser: 'Mosquito In The Room',
    coOrganisers: 'ChefsProVeggie',
  }),
  moment({
    id: 'm-zomerbar',
    title: 'Zomerbar Gentse Feesten met talks en workshops',
    startDate: '2027-07-01',
    dateUnsure: true,
    type: 'Event',
    targetGroup: 'Consument',
    focus: '100% plantaardig',
    region: 'Gent',
    organiser: 'ProVeg',
    createdBy: 'ProVeg',
    createdAt: T('2026-09-24', '09:15'),
  }),
  moment({
    id: 'm-voedingsdriehoek',
    title: '10 jaar Voedingsdriehoek',
    startDate: '2027-09-17',
    type: 'Campagne',
    targetGroup: 'Breed',
    focus: 'breder eiwitshift',
    organiser: 'Vlaams Instituut Gezond Leven',
    halfhalfLink: true,
    link: 'https://www.gezondleven.be',
  }),
];

const R = (
  id: string,
  momentId: string,
  org: string,
  name: string,
  kind: Reaction['kind'],
  createdAt: string,
  extra: Partial<Reaction> = {},
): Reaction => ({ id, momentId, org, name, kind, createdAt, inContact: false, ...extra });

export const SEED_REACTIONS: Reaction[] = [
  R('r1', 'm-on-a-budget', 'Plant-Based Universities', 'Kernteam PBU', 'join', T('2026-09-18', '14:20'), {
    note: 'Interessant voor studenten, link met Campus V Cup.',
  }),
  R('r2', 'm-superlijst', 'Lidl', 'Team Duurzaamheid', 'spread', T('2026-09-15', '09:40'), { inContact: true }),
  R('r3', 'm-superlijst', 'ProVeg', 'Team Campagnes', 'spread', T('2026-09-16', '11:05')),
  R('r4', 'm-public-plates', 'Plant-Based Universities', 'Kernteam PBU', 'join', T('2026-09-17', '16:30'), {
    note: 'Interesse om de campusrestaurants mee te nemen.',
  }),
  R('r5', 'm-public-plates', 'ProVeg', 'Team Campagnes', 'join', T('2026-09-19', '10:10')),
  R('r6', 'm-peulvrucht', 'Lidl', 'Team Duurzaamheid', 'join', T('2026-09-10', '13:00'), {
    note: 'Promotie op peulvruchten in de winkels tijdens die week.',
    inContact: true,
  }),
  R('r7', 'm-peulvrucht', 'Plant-Based Universities', 'Kernteam PBU', 'spread', T('2026-09-11', '08:50')),
  R('r8', 'm-peulvrucht', 'ProVeg', 'Team Campagnes', 'join', T('2026-09-12', '15:45'), {
    note: 'Valt samen met onze bonencampagne — graag bundelen.',
  }),
  R('r9', 'm-peulvrucht', 'Delhaize', 'Communicatieteam', 'spread', T('2026-09-14', '10:30')),
  R('r10', 'm-campus-v-cup', 'Plant-Based Universities', 'Kernteam PBU', 'join', T('2026-09-20', '12:00'), {
    note: 'We helpen de campussen van onze leden mee organiseren.',
    inContact: true,
  }),
  R('r11', 'm-campus-v-cup', 'Lidl', 'Team Duurzaamheid', 'spread', T('2026-09-23', '17:10')),
  R('r12', 'm-toekomstproef', 'Plant-Based Universities', 'Kernteam PBU', 'join', T('2026-09-21', '09:30')),
  R('r13', 'm-zomerbar', 'Plant-Based Universities', 'Kernteam PBU', 'join', T('2026-09-24', '11:40'), {
    note: 'Wij geven graag een talk.',
  }),
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: 'c1',
    momentId: 'm-on-a-budget',
    org: 'Plant-Based Universities',
    text: 'Mogen we de receptkaarten ook gebruiken in studentenrestaurants?',
    createdAt: T('2026-09-18', '14:25'),
  },
  {
    id: 'c2',
    momentId: 'm-on-a-budget',
    org: 'Lidl',
    text: 'Zeker! We sturen de bestanden deze week door.',
    createdAt: T('2026-09-22', '10:05'),
  },
  {
    id: 'c3',
    momentId: 'm-peulvrucht',
    org: 'ProVeg',
    text: "Onze campagne 'Wie is er bang van bonen?' loopt in dezelfde maand. Zullen we de boodschappen afstemmen?",
    createdAt: T('2026-09-12', '15:50'),
  },
  {
    id: 'c4',
    momentId: 'm-peulvrucht',
    org: 'Vlaams Instituut Gezond Leven',
    text: 'Graag! Het campagnemateriaal komt in december online.',
    createdAt: T('2026-09-15', '09:00'),
  },
  {
    id: 'c5',
    momentId: 'm-public-plates',
    org: COORDINATOR_ORG,
    text: 'Wie gaat er vanuit de Green Deal? Laat het hier weten, dan stemmen we af wie wat vertelt.',
    createdAt: T('2026-09-20', '08:45'),
  },
];

export const SEED_SIGNALS: Signal[] = [
  {
    id: 's1',
    momentId: 'm-voorschrift',
    kind: 'Slechte timing',
    note: 'Valt op dezelfde dag als het Public Plates Forum; het publiek overlapt deels.',
    anonymous: true,
    fromOrg: 'ProVeg',
    createdAt: T('2026-09-19', '10:20'),
    resolved: false,
  },
  {
    id: 's2',
    momentId: 'm-bonen',
    kind: 'Mogelijke tegenstrijdigheid',
    note: 'Twee bonencampagnes in februari met een andere toon; afstemmen met Week van de Peulvrucht?',
    anonymous: false,
    fromOrg: 'Lidl',
    createdAt: T('2026-09-21', '16:00'),
    resolved: false,
  },
];

const N = (
  id: string,
  toOrg: string,
  momentId: string,
  kind: AppNotification['kind'],
  fromOrg: string,
  createdAt: string,
  detail?: string,
  read = false,
  refId?: string,
): AppNotification => ({ id, toOrg, momentId, kind, fromOrg, createdAt, detail, read, refId });

export const SEED_NOTIFICATIONS: AppNotification[] = [
  N('n1', 'Lidl', 'm-on-a-budget', 'reaction', 'Plant-Based Universities', T('2026-09-18', '14:20'), 'Ik haak aan', true, 'r1'),
  N('n2', 'ProVeg', 'm-on-a-budget', 'reaction', 'Plant-Based Universities', T('2026-09-18', '14:20'), 'Ik haak aan', true, 'r1'),
  N('n3', 'Plant-Based Universities', 'm-on-a-budget', 'comment', 'Lidl', T('2026-09-22', '10:05'), 'Zeker! We sturen de bestanden deze week door.', false, 'c2'),
  N('n4', 'ProVeg', 'm-campus-v-cup', 'reaction', 'Plant-Based Universities', T('2026-09-20', '12:00'), 'Ik haak aan', true, 'r10'),
  N('n5', 'ProVeg', 'm-campus-v-cup', 'reaction', 'Lidl', T('2026-09-23', '17:10'), 'Ik kan mee verspreiden', false, 'r11'),
  N('n6', 'ProVeg', 'm-zomerbar', 'reaction', 'Plant-Based Universities', T('2026-09-24', '11:40'), 'Ik haak aan', false, 'r13'),
  N('n7', COORDINATOR_ORG, 'm-voorschrift', 'signal', 'Anoniem', T('2026-09-19', '10:20'), 'Slechte timing', true, 's1'),
  N('n8', COORDINATOR_ORG, 'm-bonen', 'signal', 'Lidl', T('2026-09-21', '16:00'), 'Mogelijke tegenstrijdigheid', false, 's2'),
  N('n9', COORDINATOR_ORG, 'm-zomerbar', 'new_moment', 'ProVeg', T('2026-09-24', '09:15'), undefined, false, 'm-zomerbar'),
];

export function seedState(): AppState {
  // Deep copy so the reducer can never mutate the seed.
  return JSON.parse(
    JSON.stringify({
      version: STATE_VERSION,
      role: 'coordinator',
      moments: SEED_MOMENTS,
      reactions: SEED_REACTIONS,
      comments: SEED_COMMENTS,
      signals: SEED_SIGNALS,
      notifications: SEED_NOTIFICATIONS,
      fieldDefs: SEED_FIELD_DEFS,
    } satisfies AppState),
  );
}
