-- Generated by scripts/gen-seed-sql.ts from src/seed.ts. Do not edit by hand.
-- The real moments from the partners' shared sheet (organisation names only).

insert into public.organisations (name, is_green_deal_partner) values
  ('Mosquito In The Room', true),
  ('Delhaize', true),
  ('GoodPlanet', true),
  ('Artevelde', true),
  ('Lidl', true),
  ('ProVeg', true),
  ('VLAM', true),
  ('GAIA', true),
  ('Questionmark', true),
  ('Rikolto', true),
  ('Run and Harvest', false),
  ('We''re Smart', false),
  ('Stad Brugge', false),
  ('JAVA Foodservice', true),
  ('Ardo', true),
  ('ILVO', true),
  ('Climate Group', false),
  ('Vlaams Instituut Gezond Leven', true),
  ('VBVD', true),
  ('ChefsProVeggie', true),
  ('Departement Omgeving', false),
  ('Plant-Based Universities', true)
on conflict (name) do nothing;

insert into public.field_defs (id, name, type, options, show_in_form) values
  ('f-taal', 'Taal', 'dropdown', array['Nederlands', 'Frans', 'Engels', 'Meertalig']::text[], true),
  ('f-pers', 'Persmoment voorzien', 'yesno', '{}'::text[], true)
on conflict (id) do nothing;

-- Seed rows keep their original "created by" and must not notify anyone.
alter table public.moments disable trigger guard_moment;
alter table public.moments disable trigger notify_moment;

insert into public.moments (id, title, start_date, end_date, ongoing, date_unsure, unsure_note, type, target_group, focus, free, region,
  organiser, co_organisers, owner_orgs, is_green_deal_partner, link, description, halfhalf_link, need, featured, custom_fields, created_by_org, created_at) values
  ('m-webinar-upf', 'Webinar ''Een open dialoog over voeding, ultrabewerkt en gezondheid''', '2026-09-23', null, false, false, null, 'Webinar', 'Breed', 'breder eiwitshift', true, 'Online', 'Mosquito In The Room', null, array['Mosquito In The Room']::text[], true, null, 'Online gesprek over voeding, ultrabewerkte producten en gezondheid.', false, null, false, '{"f-taal":"Nederlands"}'::jsonb, 'Mosquito In The Room', '2026-09-01T10:00:00'),
  ('m-goodplanet', 'Samenwerking GoodPlanet, Delhaize en Artevelde', '2026-09-22', null, false, false, null, 'Persbericht', 'Media', 'halfhalf', true, 'Vlaanderen', 'Delhaize', 'GoodPlanet, Artevelde', array['Delhaize', 'GoodPlanet', 'Artevelde']::text[], true, 'https://www.delhaize.be', 'Gezamenlijk persbericht over de samenwerking tussen GoodPlanet, Delhaize en Artevelde.', true, null, false, '{"f-pers":"ja"}'::jsonb, 'Delhaize', '2026-09-01T10:00:00'),
  ('m-on-a-budget', 'Campagne ''On a budget''', '2026-09-01', null, true, false, null, 'Campagne', 'Consument', '100% plantaardig', true, 'Vlaanderen', 'Lidl', 'ProVeg', array['Lidl', 'ProVeg']::text[], true, 'https://www.lidl.be', 'Campagne rond betaalbaar plantaardig eten.', false, null, false, '{"f-taal":"Meertalig"}'::jsonb, 'Lidl', '2026-09-01T10:00:00'),
  ('m-smos', 'Campagne ''Smos alles''', '2026-09-14', '2026-11-08', false, false, null, 'Campagne', 'Consument', 'breder eiwitshift', true, 'Vlaanderen', 'VLAM', null, array['VLAM']::text[], true, 'https://www.vlam.be', 'Focus: breder dan volledig vegetarisch.', false, null, false, '{}'::jsonb, 'VLAM', '2026-09-01T10:00:00'),
  ('m-taste-truck', 'Taste Truck', null, null, true, false, null, 'Event', 'Consument', '100% plantaardig', true, 'Vlaanderen', 'GAIA', null, array['GAIA']::text[], true, 'https://www.gaia.be', 'Foodtruck met plantaardige proevertjes, gratis te boeken voor evenementen.', false, 'Event met min. 500 bezoekers? De taste truck is gratis.', false, '{}'::jsonb, 'GAIA', '2026-09-01T10:00:00'),
  ('m-veggiedag', 'Wereld Veggiedag', '2026-10-01', null, false, false, null, 'Themadag', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Internationale themadag', null, array['Internationale themadag']::text[], false, null, null, false, null, false, '{}'::jsonb, 'Departement Omgeving', '2026-09-01T10:00:00'),
  ('m-superlijst', 'Publicatie Superlijst Milieu II', '2026-10-06', null, false, false, null, 'Publicatie', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Questionmark', 'Rikolto', array['Questionmark', 'Rikolto']::text[], true, null, 'Tweede editie van de Superlijst Milieu.', false, 'Mee verspreiden via eigen kanalen', false, '{"f-pers":"ja"}'::jsonb, 'Questionmark', '2026-09-01T10:00:00'),
  ('m-food-chains', 'Event ''Plant-Based Food Chains''', '2026-10-07', '2026-10-08', false, false, null, 'Event', 'Professionals', '100% plantaardig', false, 'Vlaanderen', 'Run and Harvest', null, array['Run and Harvest']::text[], false, null, 'Tweedaags event voor de voedselketen en het beleid.', false, null, false, '{"f-taal":"Engels"}'::jsonb, 'Run and Harvest', '2026-09-01T10:00:00'),
  ('m-aardappel', 'Aardappelcampagne', '2026-10-14', '2026-11-14', false, false, null, 'Campagne', 'Consument', 'breder eiwitshift', true, 'Vlaanderen', 'VLAM', null, array['VLAM']::text[], true, 'https://www.vlam.be', null, false, null, false, '{}'::jsonb, 'VLAM', '2026-09-01T10:00:00'),
  ('m-pure-plant', 'We''re Smart Pure Plant Days (Brugge)', '2026-10-25', '2026-10-27', false, false, null, 'Event', 'Breed', '100% plantaardig', true, 'West-Vlaanderen', 'We''re Smart', 'Stad Brugge', array['We''re Smart', 'Stad Brugge']::text[], false, null, null, false, null, false, '{"f-taal":"Meertalig"}'::jsonb, 'We''re Smart', '2026-09-01T10:00:00'),
  ('m-verrassend', 'Workshop ''Verrassend Plantaardig''', '2026-10-27', null, false, false, null, 'Workshop', 'Chefs & grootkeukens', '100% plantaardig', true, 'Vlaanderen', 'JAVA Foodservice', 'Ardo', array['JAVA Foodservice', 'Ardo']::text[], true, null, 'Workshop voor chefs en grootkeukens.', false, null, false, '{}'::jsonb, 'JAVA Foodservice', '2026-09-01T10:00:00'),
  ('m-campus-v-cup', 'Campus V Cup', '2026-11-01', null, false, true, 'meerdaags', 'Campagne', 'Hoger onderwijs', '100% plantaardig', true, 'Vlaanderen', 'ProVeg', null, array['ProVeg']::text[], true, null, 'Meerdaagse campagne op hogescholen en universiteiten.', false, '15 hogescholen/universiteiten doen mee; wie iets wil organiseren op de campussen, neem contact op.', true, '{}'::jsonb, 'ProVeg', '2026-09-01T10:00:00'),
  ('m-vegan-day', 'World Vegan Day', '2026-11-01', null, false, false, null, 'Themadag', 'Breed', '100% plantaardig', true, 'Vlaanderen', 'Internationale themadag', null, array['Internationale themadag']::text[], false, null, null, false, null, false, '{}'::jsonb, 'Departement Omgeving', '2026-09-01T10:00:00'),
  ('m-ilvo', 'Studiedag ''Plantaardige vleesanalogen''', '2026-11-12', null, false, false, null, 'Workshop', 'Professionals', 'breder eiwitshift', true, 'Vlaanderen', 'ILVO', null, array['ILVO']::text[], true, 'https://ilvo.vlaanderen.be', 'Studiedag over plantaardige vleesanalogen.', false, null, false, '{}'::jsonb, 'ILVO', '2026-09-01T10:00:00'),
  ('m-voorschrift', 'Congres ''Voeding op voorschrift''', '2026-12-15', null, false, false, null, 'Event', 'Zorg', 'breder eiwitshift', false, 'Vlaanderen', 'Mosquito In The Room', null, array['Mosquito In The Room']::text[], true, null, null, false, null, false, '{}'::jsonb, 'Mosquito In The Room', '2026-09-01T10:00:00'),
  ('m-public-plates', 'Public Plates Forum', '2026-12-15', null, false, false, null, 'Event', 'Professionals', 'breder eiwitshift', true, 'Brussel', 'Climate Group', null, array['Climate Group']::text[], false, null, 'Forum over duurzame maaltijden in publieke keukens.', false, null, false, '{"f-taal":"Engels"}'::jsonb, 'Climate Group', '2026-09-01T10:00:00'),
  ('m-goed-eten', 'Week voor Goed Eten', '2027-01-15', '2027-01-24', false, false, null, 'Campagne', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Rikolto', null, array['Rikolto']::text[], true, null, null, false, null, false, '{}'::jsonb, 'Rikolto', '2026-09-01T10:00:00'),
  ('m-peulvrucht', 'Week van de Peulvrucht', '2027-02-08', '2027-02-14', false, false, null, 'Campagne', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Vlaams Instituut Gezond Leven', null, array['Vlaams Instituut Gezond Leven']::text[], true, 'https://www.gezondleven.be', 'Een week lang aandacht voor peulvruchten.', true, null, true, '{"f-taal":"Nederlands","f-pers":"ja"}'::jsonb, 'Vlaams Instituut Gezond Leven', '2026-09-01T10:00:00'),
  ('m-bonen', 'Campagne ''Beans & Pulses – Wie is er bang van bonen?''', '2027-02-01', null, false, true, null, 'Campagne', 'Consument', '100% plantaardig', true, 'Vlaanderen', 'ProVeg', null, array['ProVeg']::text[], true, null, null, false, null, false, '{}'::jsonb, 'ProVeg', '2026-09-01T10:00:00'),
  ('m-pulses-day', 'World Pulses Day', '2027-02-10', null, false, false, null, 'Themadag', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Internationale themadag', null, array['Internationale themadag']::text[], false, null, null, false, null, false, '{}'::jsonb, 'Departement Omgeving', '2026-09-01T10:00:00'),
  ('m-dietist', 'Week van de Diëtist', '2027-03-15', '2027-03-22', false, false, null, 'Campagne', 'Zorg', 'breder eiwitshift', true, 'Vlaanderen', 'VBVD', null, array['VBVD']::text[], true, null, null, false, null, false, '{}'::jsonb, 'VBVD', '2026-09-01T10:00:00'),
  ('m-overshoot', 'Earth Overshoot Day (België)', '2027-04-11', null, false, false, null, 'Themadag', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Internationale themadag', null, array['Internationale themadag']::text[], false, null, null, false, null, false, '{}'::jsonb, 'Departement Omgeving', '2026-09-01T10:00:00'),
  ('m-toekomstproef', 'Toekomstproef – inspiratie-event voor grootkeukens', '2027-05-01', null, false, true, '11 of 12 mei', 'Event', 'Chefs & grootkeukens', 'breder eiwitshift', true, 'Vlaanderen', 'Mosquito In The Room', 'ChefsProVeggie', array['Mosquito In The Room', 'ChefsProVeggie']::text[], true, null, null, false, null, false, '{}'::jsonb, 'Mosquito In The Room', '2026-09-01T10:00:00'),
  ('m-zomerbar', 'Zomerbar Gentse Feesten met talks en workshops', '2027-07-01', null, false, true, null, 'Event', 'Consument', '100% plantaardig', true, 'Gent', 'ProVeg', null, array['ProVeg']::text[], true, null, null, false, null, false, '{}'::jsonb, 'ProVeg', '2026-09-24T09:15:00'),
  ('m-voedingsdriehoek', '10 jaar Voedingsdriehoek', '2027-09-17', null, false, false, null, 'Campagne', 'Breed', 'breder eiwitshift', true, 'Vlaanderen', 'Vlaams Instituut Gezond Leven', null, array['Vlaams Instituut Gezond Leven']::text[], true, 'https://www.gezondleven.be', null, true, null, false, '{}'::jsonb, 'Vlaams Instituut Gezond Leven', '2026-09-01T10:00:00')
on conflict (id) do nothing;

alter table public.moments enable trigger guard_moment;
alter table public.moments enable trigger notify_moment;
